# Generated by Django 5.2.1 on 2025-11-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('producer', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('red_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('memory', models.CharField(blank=True, max_length=50, null=True)),
                ('art', models.CharField(blank=True, max_length=50, null=True)),
                ('diagonal', models.CharField(blank=True, max_length=50, null=True)),
                ('display', models.CharField(blank=True, max_length=50, null=True)),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('comment_count', models.IntegerField(default=0)),
                ('images', models.JSONField(blank=True, null=True)),
                ('description', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
