# Generated by Django 5.2.1 on 2025-11-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_product_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comment_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
